In [9]:
import pandas as pd
import numpy as np

In [10]:
dg_df = pd.read_csv('./big-ideas-lab-glycemic-variability-and-wearable-device-data-1.1.2/Demographics.csv')
dg_df.head(16)

    ID  Gender  HbA1c
0   13    MALE    5.7
1    1  FEMALE    5.5
2    3  FEMALE    5.9
3    4  FEMALE    6.4
4    5  FEMALE    5.7
5    2    MALE    5.6
6    6  FEMALE    5.8
7    7  FEMALE    5.3
8    8  FEMALE    5.6
9   10  FEMALE    6.0
10   9    MALE    6.1
11  11    MALE    6.0
12  12    MALE    5.6
13  14    MALE    5.5
14  15  FEMALE    5.5
15  16    MALE    5.5

In [11]:
df = pd.read_csv('./features_na_included.csv', sep='\t', encoding='utf-8')

In [12]:
df['meanHRV'].isna().sum()

4336

In [13]:
for id in range(1, len(dg_df)+1):
    if id == 15:
        continue
    ibi_df = pd.read_csv(f'./big-ideas-lab-glycemic-variability-and-wearable-device-data-1.1.2/{id:03}/IBI_{id:03}.csv')

    print(f'[ID: {id}] Now processing ...')

    # 데이터 처리
    ibi_df['datetime'] = pd.to_datetime(ibi_df['datetime'])
    ibi_df.set_index('datetime', inplace=True)

    # 5분 간격으로 리샘플링하고 각 구간의 개수 계산
    resampled = ibi_df[' ibi'].resample('5T').count()

    # 결과를 DataFrame으로 변환
    resampled_df = resampled.reset_index()
    resampled_df.columns = ['datetime', 'count']

    # 결과를 파일로 저장
    resampled_df.to_csv(f'./ibi_resampled_counts/ID_{id:03}_5min_counts.csv', index=False)
    
    print(f'[ID: {id}] Resampled data saved.')

[ID: 1] Now processing ...
[ID: 1] Resampled data saved.
[ID: 2] Now processing ...
[ID: 2] Resampled data saved.
[ID: 3] Now processing ...
[ID: 3] Resampled data saved.
[ID: 4] Now processing ...
[ID: 4] Resampled data saved.
[ID: 5] Now processing ...
[ID: 5] Resampled data saved.
[ID: 6] Now processing ...
[ID: 6] Resampled data saved.
[ID: 7] Now processing ...
[ID: 7] Resampled data saved.
[ID: 8] Now processing ...
[ID: 8] Resampled data saved.
[ID: 9] Now processing ...
[ID: 9] Resampled data saved.
[ID: 10] Now processing ...
[ID: 10] Resampled data saved.
[ID: 11] Now processing ...
[ID: 11] Resampled data saved.
[ID: 12] Now processing ...
[ID: 12] Resampled data saved.
[ID: 13] Now processing ...
[ID: 13] Resampled data saved.
[ID: 14] Now processing ...
[ID: 14] Resampled data saved.
[ID: 16] Now processing ...
[ID: 16] Resampled data saved.